language: c
compiler:
  - gcc
  - clang

sudo: required

before_install:
  # install a newer cmake since at this time Travis only has version 2.8.7
  - yes | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
install: sudo apt-get install libXxf86vm-dev cmake
script:
  - mkdir build && cd build && cmake ../ && make && cd ..
  - chmod +x script/test.sh
  - ./script/test.sh